name: ci 
on:
  pull_request:
    branches:
      - main   
  push:
    branches:
      - main 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: build
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 这个是sftp插件
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.KYREFLECTION_MK1_RSA }}
          local_path: 'site/*'
          remote_path: '/var/www/mug/cytus2-charting-guide-site'

