name: ci 
on:
  pull_request:
    branches:
      - main   
  push:
    branches:
      - main 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.KYREFLECTION_MK1_RSA }}
      REMOTE_HOST: 142.171.104.92
      REMOTE_USER: root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: build
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Removing /var/www/mug/cytus2-charting-guide-site"
          ssh $REMOTE_USER@$REMOTE_HOST "rm -f /var/www/mug/cytus2-charting-guide-site || echo 'no such directory.'"
          echo "Creating /var/www/mug/cytus2-charting-guide-site"
          ssh $REMOTE_USER@$REMOTE_HOST "mkdir -p /var/www/mug/cytus2-charting-guide-site"
          echo "Copying 'site' directory to /var/www/mug/cytus2-charting-guide-site"
          scp -r site/* $REMOTE_USER@$REMOTE_HOST:/var/www/mug/cytus2-charting-guide-site/
