name: ci 
on:
  pull_request:
    branches:
      - main   
  push:
    branches:
      - main 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: build
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      # - run: pip install mkdocs-blogging-plugin  # 记得安装其他依赖的库
      - run: mkdocs gh-deploy --force
        
